spring.application.name=srvc

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:habits.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Disable datasource initialization (not needed for SQLite)
spring.sql.init.mode=never
